### ISSUE TITLE
Support editing of match metadata

### ISSUE THREAD

**Issue by raymondben** [openvolley/ovscout#3]

**Comment by ick003** [comment]
Can we include the modification of team line ups and roster as well?

**Comment by raymondben** [comment]
As of https://github.com/openvolley/ovscout/commit/f4aed42936fa3a13a0fba67c1dc7b02557f2924c the rosters are editable. Actual on-court lineups is more difficult, because it has to be propagated throughout the whole data frame and rotations recalculated at every point.

**Comment by raymondben** [comment]
Remaining tasks here are primarily about lineup editing, changing assignment.

**Comment by ick003** [comment]
Well... ;) Actually, the possiblity to add/remove players from the roster would be nice too. Unless it is available already, in which case what are the keys to do so?

**Comment by ick003** [comment]
Starting lineup and substitutions now available.
